services:
  - type: web
    name: uncycle
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn uncycle:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 